project:
  type: book

book:
  title: "Test_book"
  author: "Norah Jones"
  date: "8/23/2023"
  chapters:
    - index.qmd
    - chapters/01_intro/intro.qmd
    - chapters/02_summary/summary.qmd
    - chapters/03_machine_learning_in_finance/machine_learning_in_finance.ipynb
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



